2024-12-08 09:07:09,761:DEBUG:certbot._internal.main:certbot version: 3.0.1
2024-12-08 09:07:09,761:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2024-12-08 09:07:09,761:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/html', '--non-interactive', '--email', 'tbongkim03@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'parkingissue.online']
2024-12-08 09:07:09,761:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-12-08 09:07:09,771:DEBUG:certbot._internal.log:Root logging level set at 30
2024-12-08 09:07:09,772:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2024-12-08 09:07:09,772:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A separate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x789be3e8ca70>
Prep: True
2024-12-08 09:07:09,774:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x789be3e8ca70> and installer None
2024-12-08 09:07:09,774:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2024-12-08 09:07:09,818:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2100901597', new_authzr_uri=None, terms_of_service=None), c809cf84a89ab438984ee845a16fa1ea, Meta(creation_dt=datetime.datetime(2024, 12, 8, 8, 56, 1, tzinfo=<UTC>), creation_host='729df04b4f14', register_to_eff=None))>
2024-12-08 09:07:09,818:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-12-08 09:07:09,820:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-12-08 09:07:10,367:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 746
2024-12-08 09:07:10,367:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 09:07:10 GMT
Content-Type: application/json
Content-Length: 746
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "_K3MrOeqJi4": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2024-12-08 09:07:10,368:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for parkingissue.online
2024-12-08 09:07:10,372:DEBUG:acme.client:Requesting fresh nonce
2024-12-08 09:07:10,374:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-12-08 09:07:11,888:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2024-12-08 09:07:11,888:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 09:07:11 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: Uqfi4YotscxZWX1c0oIH8-v5QgfKAE4O_YGh6FcH-zYJD2vOERI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2024-12-08 09:07:11,888:DEBUG:acme.client:Storing nonce: Uqfi4YotscxZWX1c0oIH8-v5QgfKAE4O_YGh6FcH-zYJD2vOERI
2024-12-08 09:07:11,888:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "parkingissue.online"\n    }\n  ]\n}'
2024-12-08 09:07:11,890:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjEwMDkwMTU5NyIsICJub25jZSI6ICJVcWZpNFlvdHNjeFpXWDFjMG9JSDgtdjVRZ2ZLQUU0T19ZR2g2RmNILXpZSkQydk9FUkkiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "CNSmHutGHJvGCGqmlp1YgXsRUUZacZLUKxoRwGSf9NU7i1ICiHiDHetILx7rOrhoff44X7rtBi7nR-9as8YNpcOs2lTlH-bIvDYH533zfhT2o9minJZuta7vdyIXodyR6ny6eTYZm_-eb9sJDEH5VWvgKF7IAs6Z_3MQ0cTOOrMVJXVDXThObmTdasPME2H1a-YNtRWdqFbT-I3l3JWzz_nCGMAenD6v5yTdwRXACM4A06B9fIe1G6RrczQkJdufMZ3cv0pE8pNF413cOxVviNTLHyNeAkf7TQeicCEvlAQZayXWavdBWNvlqgXbPMEliz4-yz6pvBLpioLht6tBUg",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInBhcmtpbmdpc3N1ZS5vbmxpbmUiCiAgICB9CiAgXQp9"
}
2024-12-08 09:07:12,093:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 429 300
2024-12-08 09:07:12,093:DEBUG:acme.client:Received response:
HTTP 429
Server: nginx
Date: Sun, 08 Dec 2024 09:07:12 GMT
Content-Type: application/problem+json
Content-Length: 300
Connection: keep-alive
Boulder-Requester: 2100901597
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://letsencrypt.org/docs/rate-limits>;rel="help"
Replay-Nonce: vyQW5O6tF72_wfEOOr5un_PVn4PGZbZotu8svA6KuCcS5g6l0yI
Retry-After: 51

{
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "too many failed authorizations (5) for \"parkingissue.online\" in the last 1h0m0s, retry after 2024-12-08 09:08:03 UTC: see https://letsencrypt.org/docs/rate-limits/#authorization-failures-per-hostname-per-account",
  "status": 429
}
2024-12-08 09:07:12,093:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1876, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1578, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 142, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 478, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 137, in new_order
    response = self._post(self.directory['newOrder'], order)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 365, in _post
    return self.net.post(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 738, in post
    return self._post_once(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 751, in _post_once
    response = self._check_response(response, content_type=content_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 602, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: too many failed authorizations (5) for "parkingissue.online" in the last 1h0m0s, retry after 2024-12-08 09:08:03 UTC: see https://letsencrypt.org/docs/rate-limits/#authorization-failures-per-hostname-per-account
2024-12-08 09:07:12,096:ERROR:certbot._internal.log:An unexpected error occurred:
2024-12-08 09:07:12,096:ERROR:certbot._internal.log:too many failed authorizations (5) for "parkingissue.online" in the last 1h0m0s, retry after 2024-12-08 09:08:03 UTC: see https://letsencrypt.org/docs/rate-limits/#authorization-failures-per-hostname-per-account
